### ISSUE TITLE
SFO Reader - Title displaying issue

### ISSUE THREAD

**Issue by tomazzz369** [xXxTheDarkprogramerxXx/PS3Tools#1]
https://github.com/xXxTheDarkprogramerxXx/PS3Tools/tree/master/SFO%20Editor/SFO%20Reader

Titles that contain non standard characters are not displayed properly, instead title we got ?????.
For example: instead ABZÛ we got ABZ?

any chance for fixing this?

regards

**Comment by xXxTheDarkprogramerxXx** [comment]
HI there @tomazzz369  i'm still developing this for both ps4 and ps3 sfo's as soon as this is ready i will publish it and make a release on GitHub as well as an article on Playstationhax.xyz 

Which SFO did you try and read ?

**Comment by tomazzz369** [comment]
sfo:
http://www53.zippyshare.com/v/0l4HeEpZ/file.html

same in PARAM.SFO Editor:

ABZ?? instead of ABZÛ
Dark Souls III??? Official Soundtrack instead of Dark Souls III™ Official Soundtrack

**Comment by tomazzz369** [comment]
now working fine. thanks
