### ISSUE TITLE
Always crashes.

### ISSUE THREAD

**Issue by MrTestrus** [xXxTheDarkprogramerxXx/PS3Tools#11]
Tool ps4 ps2 not working for me. Win7.
How to fix this?
Code error: https://i.imgur.com/OLKyqcK.jpg

**Comment by xXxTheDarkprogramerxXx** [comment]
Did you change your path in settings ?

Also when does it crash ?

**Comment by MrTestrus** [comment]
I tried to change the way. To no avail.
It crashes right after the start of the conversion.

**Comment by MrTestrus** [comment]
Temp path settings - It helped. Thank you.

**Comment by xXxTheDarkprogramerxXx** [comment]
Glar you got it working 

Enjoy
