### ISSUE TITLE
Startindex cannot be less than zero

### ISSUE THREAD

**Issue by joecox1981** [xXxTheDarkprogramerxXx/PS3Tools#14]
Hi, I have encountered another problem on the PS2 classics GUI for PS4.  The issue is with multi-disc PKGs  Whenever I click to complile the PKG file, the programe reports an error and will not continue: StartIndex cannot be less than zero.  Parameter name: startIndex.  The same problem arises no matter which multi disc games I try to convert to PKG format.  The program works fine when compling single disc PKGs.   Thanks again for your help.

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi @joecox1981  
i will look into this as soon as i have some open time 

Thanks for opening an issue

**Comment by xXxTheDarkprogramerxXx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PS2 Classics Gui](https://trello.com/c/37jjtYg9/7-ps2-classics-gui)

**Comment by xXxTheDarkprogramerxXx** [comment]
@joecox1981  i can not reproduce this error on my end no matter what combination of iso numbers i try 

Could you please check what version your using i will keep the issue open untill you reply 

Kind Regards 
xDPx

**Comment by joecox1981** [comment]
Hi, sorry for the delayed response.  I wanted to try on another PC but unfortunately I get exactly the same error message when I try to compile a PKG containing multiple ISOs.  

The stated version number is 1.0.0.0 and I the program has auto-updated to the latest version at some point recently.  Thanks for your help.

**Comment by joecox1981** [comment]
Sorry small correction to the above - I can now see I'm using version 1.0.0.12.  APologies if this has caused any confusion.
