### ISSUE TITLE
PS4 PSP HD EMU .PBP ERROR

### ISSUE THREAD

**Issue by Kazumatr** [xXxTheDarkprogramerxXx/PS3Tools#15]
PSX game .pbp files not work program every time error.

**Comment by xXxTheDarkprogramerxXx** [comment]
Do you have a specific place where it broke this is very vague ?

**Comment by Kazumatr** [comment]
When create ps4 pkg button stopped program windows is search error.

**Comment by xXxTheDarkprogramerxXx** [comment]
Will have a look at this asap

**Comment by Kazumatr** [comment]
https://i.resimyukle.xyz/C0PdbW.png

**Comment by xXxTheDarkprogramerxXx** [comment]
@kazumatr this is a bug will be fixed soon

**Comment by xXxTheDarkprogramerxXx** [comment]
@Kazumatr Issue has been fixed expect a release soon
