### ISSUE TITLE
PSP HD problems

### ISSUE THREAD

**Issue by maks9597** [xXxTheDarkprogramerxXx/PS3Tools#16]
When i delete files and download new version i got message like "You cannot start from this location, the application is already installed from another location, and it does not start" what should i do with it?
log here: 
Platform version
	Windows 			: 6.2.9200.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

ИСТОЧНИКИ
	URL-адрес развертывания			: file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PlayStation%20Family/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application

УДОСТОВЕРЕНИЯ
	Удостоверение развертывания		: PS4 PSP Classics GUI.application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cbf201671a91a80e, processorArchitecture=msil

СВОДКА ПРИЛОЖЕНИЯ
	* Устанавливаемое приложение.

СВОДКА ОШИБОК
	Ниже приводится сводка ошибок, сведения об этих ошибках перечислены далее в журнале.
	* В результате активизации C:\Users\Ронни\Desktop\PlayStation Family\PS4\PSPHD\PS4 PSP Classics GUI.application произошла ошибка с исключением. Определены следующие сообщения о сбоях:
		+ Нельзя запустить приложение PS4 PSP Classics GUI из этого расположения. Данное приложение уже установлено из другого расположения.
		+ Приложение PS4 PSP Classics GUI невозможно запустить из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PlayStation%20Family/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application. Оно уже установлено из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application. Можно запустить его из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application или удалить приложение и установить повторно из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PlayStation%20Family/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application. После повторной установки приложения любые его настройки могут быть утеряны.

СВОДКА СБОЯ ТРАНЗАКЦИИ СОХРАНЕНИЯ КОМПОНЕНТА
	Не определена никакая ошибка транзакции.

ПРЕДУПРЕЖДЕНИЯ
	Во время этой операции предупреждения не выводились.

СОСТОЯНИЕ ВЫПОЛНЕНИЯ ОПЕРАЦИИ
	* [15.09.2018 21:54:57] : Активация C:\Users\Ронни\Desktop\PlayStation Family\PS4\PSPHD\PS4 PSP Classics GUI.application начата.
	* [15.09.2018 21:54:57] : Обработка манифеста развертывания успешно завершена.

СВЕДЕНИЯ ОБ ОШИБКЕ
	Во время выполнения этой операции обнаружены следующие ошибки.
	* [15.09.2018 21:54:57] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Нельзя запустить приложение PS4 PSP Classics GUI из этого расположения. Данное приложение уже установлено из другого расположения.
		- Источник: System.Deployment
		- Запись изменений стека:
			в System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			в System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			в System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Внутреннее исключение ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Приложение PS4 PSP Classics GUI невозможно запустить из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PlayStation%20Family/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application. Оно уже установлено из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application. Можно запустить его из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application или удалить приложение и установить повторно из расположения file:///C:/Users/%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8/Desktop/PlayStation%20Family/PS4/PSPHD/PS4%20PSP%20Classics%20GUI.application.

**Comment by xXxTheDarkprogramerxXx** [comment]
Please uninstall from here 
https://www.laptopmag.com/articles/uninstall-programs-windows-10

And try again

Please use setup.exe

**Comment by maks9597** [comment]
> Please uninstall from here
> https://www.laptopmag.com/articles/uninstall-programs-windows-10
> 
> And try again
> 
> Please use setup.exe

thanks, got it

**Comment by xXxTheDarkprogramerxXx** [comment]
Glad i could help
