### ISSUE TITLE
Updating...

### ISSUE THREAD

**Issue by TheCyndicate** [xXxTheDarkprogramerxXx/PS3Tools#18]
Greetings, Thank you for putting time into this tool and contributing to the growing library of PS4 tools. I really do appreciate it.

I just have one request. Some of us use systems that are purposely isolated from the internet and as such, cannot directly download an update from within the application. Please consider putting updates up for download via a browser.

and again, thank you for all of the hard work you are putting into this.

**Comment by xXxTheDarkprogramerxXx** [comment]
this will be considered
