### ISSUE TITLE
PS2 Classic GUI PS4 : Multi ISO not working

### ISSUE THREAD

**Issue by BigBoss-o** [xXxTheDarkprogramerxXx/PS3Tools#187]
Hey, whats up Darkprogramer ! i appreciate all your hard works for this GUI and other Programs you made, i really like the interface and all the features it have

but i face some issues like the one i written in the topic :

- Multi ISO not working at all, the problem is when i select multiple ISOs the small window will popup containing the names of the ISOs as always, then i write the NP title "FOR EXAMPLE"(DSRA12345) and then press Create BUTTON and select the Output path, NOW here is the problem, it just popup to the Output path of the game with the trophy sound like it is done. there is even no converting process or any PKG file.

I tried many solutions like changing output path, also try to run it as an Administrator, and close firewall and windows defender etc..

Version of the app : 1.0.0.27
My Operating System : Windows 10-64bit

Thank you again.

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi There,
Thanks for the info ill look into it as soon as i have an opening.
Thanks for using my tools :)

**Comment by BigBoss-o** [comment]
Thank to you.

All the best ..

**Comment by Aurangzeb56** [comment]
Lol, encountered the same error on my side. As soon as I click create ps2 classic, it's done and a window pops up, but nothing is made after that. ^^" Tried finding the older version 1.0.0.10 but no luck finding that version on net.

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi there an update has been pushed please let me know if this works for you

**Comment by Aurangzeb56** [comment]
> Hi there an update has been pushed please let me know if this works for you

Just checked it. It's working flawlessly for me. Made a PKG with both of Grandia 3's discs. They load fine, play fine and also the option of changing discs is also there. Though I noticed one thing, in the previous versions, when I used to make PKG, they had a string of numbers including the Game ID as it's name. But the name of the PKG for this one was the same as the title name that I wrote in the PS2 GUI. It doesn't bother me, just thought you should know. Kudos :D

**Comment by xXxTheDarkprogramerxXx** [comment]
@Aurangzeb56 yes thats a new future just makes it more user friendly :) glad its working for you enjoy 
Then I'm closing this as well
