### ISSUE TITLE
Can't change background

### ISSUE THREAD

**Issue by Aurangzeb56** [xXxTheDarkprogramerxXx/PS3Tools#195]
Hey there, I gotta tell you firsthand, great job. Really love this program of yours. I just encountered a bug in the latest version 1.0.0.27. It's just that in he file menu, we can change the cover (Icon) of the PKG file, but we can't change the background image of he PKG. Would you please look into it? Thanks :)

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi There, 
I tried duplicating your background issue problem and it seemed fine for me.
You can right click on the game icon to change the icon or the background image.
Please give it a go and let me know if this resolves your issue :)

**Comment by Aurangzeb56** [comment]
> Hi There,
> I tried duplicating your background issue problem and it seemed fine for me.
> You can right click on the game icon to change the icon or the background image.
> Please give it a go and let me know if this resolves your issue :)

Thank you soo much for replying. :)

Also I just checked, it's the same error. Nothing appears when I right click on the game icon. I don't know if this is normal or not but my game icon actually doesn't have anything on it. I have attached the pic below

![Background Icon error](https://user-images.githubusercontent.com/20149069/83603580-1edd9a80-a58e-11ea-89f9-180ed29ef654.JPG)

**Comment by xXxTheDarkprogramerxXx** [comment]
Please select an iso first then you should be able to do the rest

**Comment by Aurangzeb56** [comment]
> Please select an iso first then you should be able to do the rest

I actually feel stupid now. ^^" I though the process was the same like the older version where we could change the Icon and the Background without selecting the ISO first, but I just saw that you have to select a legit ISO first, as in a non edited ISO without the codebreaker injected for it to work. Because I just closed and re opened the program and I selected the codebreaker injected one first, but again it doesn't let me right click on the game icon. I think it works on detecting the Game ID first which enables you to change the icon and the background?

Thanks, this problem has been solved. We just have to select a non edited ISO first for the program to enable background and cover change and then we can change the ISO to the codebreaker injected one. :)

Now the only problem left for me is the multi ISO pkg error. Hope you fix that soon too. :)

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi There ,

It does use the GameId to get an image but if none is found for whatever reason you can use the file menu and select the icon from there then you change the background via the right click option 
hope this helps so you don't have to select different files each time 

Also the multi iso should be fixed but i haven't had time to test it here

**Comment by Aurangzeb56** [comment]
> Hi There ,
> 
> It does use the GameId to get an image but if none is found for whatever reason you can use the file menu and select the icon from there then you change the background via the right click option
> hope this helps so you don't have to select different files each time
> 
> Also the multi iso should be fixed but i haven't had time to test it here

Oh thank you for that tip. :) Also I just tried making the Multi ISO pkg, but the same error occurs again. The window closes as soon as we clock make PKG and it opens up the location where we saved PKG but nothing is there.

**Comment by xXxTheDarkprogramerxXx** [comment]
Ill have a look in the mean time im closing this issue you can check the multi iso issue for the updates on that
