### ISSUE TITLE
Issue for icons

### ISSUE THREAD

**Issue by chronoss09** [xXxTheDarkprogramerxXx/PS3Tools#2]
Your program work great but just one thing to make it better, can you make a auto-resize for icons ?

Size for icons : 
ICON0 : 512x512
PIC1 : 1920x1080

**Comment by xXxTheDarkprogramerxXx** [comment]
this is actually in now sorry its still early access follow me on twitter for fast updates :P 

thanks for the awesome feedback and support

**Comment by chronoss09** [comment]
Thanks too !
