### ISSUE TITLE
problem of game conversión ps2 to ps4 - test 04-10-2019

### ISSUE THREAD

**Issue by deatspartan** [xXxTheDarkprogramerxXx/PS3Tools#20]
Hi all.

greetings, I need help or information about these errors that I will try to attach in image

![Captura](https://user-images.githubusercontent.com/49502884/55924015-5e486b00-5bc5-11e9-914b-45e0cd84f47c.JPG)

![PS4 PS2 Classis GUI2](https://user-images.githubusercontent.com/49502884/55924032-71f3d180-5bc5-11e9-819e-dcf4487e47bf.JPG)

**Comment by xXxTheDarkprogramerxXx** [comment]
@deatspartan please make sure your using the latest build this build your using is a super old build
