### ISSUE TITLE
"Not enough memory resources are available to process this command"

### ISSUE THREAD

**Issue by nanashi89** [xXxTheDarkprogramerxXx/PS3Tools#21]
Tried creating a PS2 PKG with Ys Ark of Napishtim (US) with this, and that's the message I got.

Attempting to install it gives me an (CE-34706-0) error message.

What am I doing wrong?

EDIT: USING THE PS4 PS2 Classics GUI, BTW.

**Comment by xXxTheDarkprogramerxXx** [comment]
Which version are you using of the GUI ?

Firmware version on your PS4 ?

**Comment by nanashi89** [comment]
In that order,

latest version of the GUI,

and Firmware is 5.05

**Comment by xXxTheDarkprogramerxXx** [comment]
Do you know what the PS2 Title Id is ?

**Comment by nanashi89** [comment]
SLUS-20980

**Comment by xXxTheDarkprogramerxXx** [comment]
I Have Made a successful build with the latest unreleased version of PS2 Classics Gui 

I believe the issue might have been fixed with all the new changes that are coming 

next version will be 1.0.016 and i tested this build with the default emulator (which is a new setting )
