### ISSUE TITLE
undubed game can't be played just shoe up error code ce 34878-0

### ISSUE THREAD

**Issue by festum123** [xXxTheDarkprogramerxXx/PS3Tools#212]
first i try dark cloud 2 undub this game work perfectly and i try to install suikoden v and stella deus undub when i start the game just show up the error code ce 34878-0 i create the pkg file with default setting in applycation V1.0.0.28 wiyh ps4 hen 6.72

**Comment by xXxTheDarkprogramerxXx** [comment]
Unfortunately this is out of my hands as the tool was just created to help with the repacking of base games.
