### ISSUE TITLE
PS4.PS2 Classic GUI - problem in how to play more than 2 players (Multi)

### ISSUE THREAD

**Issue by BigBoss-o** [xXxTheDarkprogramerxXx/PS3Tools#213]
Hi all, 
how are you @xXxTheDarkprogramerxXx ..

First,
i would like to thank you for all the hard work you gave  ..

Second,
i have this confusing issue : is there any configuration or setting in the "PS2 Classic GUI" app that allow me to use more than 2 controllers.
Unlike the "PS3", you can play more than 2 players. May be this is a "PS4" issue not the "app" or the "PKG".

all the best.

**Comment by faddieid** [comment]
I hv the same problem is possible, i can’t plqy more than 2player💔💔

**Comment by xXxTheDarkprogramerxXx** [comment]
> Hi all,
> how are you @xXxTheDarkprogramerxXx ..
> 
> First,
> i would like to thank you for all the hard work you gave ..
> 
> Second,
> i have this confusing issue : is there any configuration or setting in the "PS2 Classic GUI" app that allow me to use more than 2 controllers.
> Unlike the "PS3", you can play more than 2 players. May be this is a "PS4" issue not the "app" or the "PKG".
> 
> all the best.

Hi there hope you are well.

Unfortunately this is out of my hands as i dont think their is a function to allow more than 2 players iol have to dig around and see what I can find
