### ISSUE TITLE
PSPHD crashes upon upload

### ISSUE THREAD

**Issue by locbox** [xXxTheDarkprogramerxXx/PS3Tools#214]
tried multiple times now, but PSPHD crashes every time i hit the upload button. I'm on 1.0.0.0 is there an update or fix?

**Comment by xXxTheDarkprogramerxXx** [comment]
> tried multiple times now, but PSPHD crashes every time i hit the upload button. I'm on 1.0.0.0 is there an update or fix?

Could you supply more images please or a better description? 
Cause I'm prerry sure their isn't an upoad button ?
Do you mean it wont load your iso ? Or are you struggling to create a pkg ? 
What settings have you enabled ?
