### ISSUE TITLE
PSPHD Freezes and Crashes trying to convert PSP ISO for PS4. Was working before update.

### ISSUE THREAD

**Issue by TheOmegaShirou01** [xXxTheDarkprogramerxXx/PS3Tools#225]
![147923898-48127891-a9ca-47f4-9736-65eb63ec5436](https://user-images.githubusercontent.com/102248639/182716741-454fea2d-cbf3-45fb-aa93-eaaca1ac399f.png)

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi there could you please provide me with the following.

Game:
NP Disc ID:
Region:
Steps to reproduce:
Operating system:

Thanks in advance

**Comment by xXxTheDarkprogramerxXx** [comment]
Closing this ticket as there has been no response
