### ISSUE TITLE
"not enough memory resources are available to process this command 2"

### ISSUE THREAD

**Issue by Longnuts** [xXxTheDarkprogramerxXx/PS3Tools#23]
The previous versions of the gui worked fine, one day I went to use it, it asked if I wanted to update, I did so, now I get that error, even if I uninstall, and reinstall, and do not update it will not work for me anymore, no matter what the ISO is. I have 16 gigs of ram, I've tried running as administrator, compatibility mode. I give up. Iv'e seen other people with the same problem, and no solutions?

**Comment by xXxTheDarkprogramerxXx** [comment]
Duplicated issue

https://github.com/xXxTheDarkprogramerxXx/PS3Tools/issues/21#event-2484944166
