### ISSUE TITLE
PS4 PS2 CLASSICS GUI-  error with converting to pkg 

### ISSUE THREAD

**Issue by Daniel70200** [xXxTheDarkprogramerxXx/PS3Tools#24]
am using the last update with jak and daxter emu,  ther error is happening when the program is converting  to pkg, in few seconds it says that its done  the process which is quite strange cause it should last more time. I thought it was normal the first time and I proceeded to install the pkg but it gave me an error (ce-34706-0) then i try many times more but the same results,

**Comment by xXxTheDarkprogramerxXx** [comment]
Thanks for opening a ticket 
I'm currently investigating the issue with created pkg's where they don't seem to want to open on the ps4 after being created

**Comment by xXxTheDarkprogramerxXx** [comment]
Hotfix incoming
