### ISSUE TITLE
PS4 PS2 Classics still not working

### ISSUE THREAD

**Issue by nanashi89** [xXxTheDarkprogramerxXx/PS3Tools#25]
Trying to convert RockMan: Power Battle Fighters (Converted from BIN to ISO). It said "unhandled execution, yada yada...." and would not let me convert my ISO.

Title ID is SLPM-62491

**Comment by xXxTheDarkprogramerxXx** [comment]
Id wager its your iso thats the problem 
Did it give you the exception whe  loading the ISO or when creating the pkg ?

**Comment by xXxTheDarkprogramerxXx** [comment]
For te life of me I can not find this rom to test this

**Comment by nanashi89** [comment]
> 
> 
> Id wager its your iso thats the problem
> Did it give you the exception whe loading the ISO or when creating the pkg ?

Apparently, the GUI does not accept BINs, so I had it converted to an ISO.

And both loading the ISO and creating the PKG.



> 
> 
> For the life of me I can not find this rom to test this

Try checking a forum of a certain "paradise." Don't think direct linking is allowed.

**Comment by xXxTheDarkprogramerxXx** [comment]
> > Id wager its your iso thats the problem
> > Did it give you the exception whe loading the ISO or when creating the pkg ?
> 
> Apparently, the GUI does not accept BINs, so I had it converted to an ISO.
> 
Uhm it should allow bin files but if i remember correctly you need to select the cue file for this to comvert the bin cue to iso 

> And both loading the ISO and creating the PKG.
> 
Once I get the rom ill see if i can reproduce the issue are you using the default emulator in settings ?
> > For the life of me I can not find this rom to test this
> 
> Try checking a forum of a certain "paradise." Don't think direct linking is allowed.

**Comment by xXxTheDarkprogramerxXx** [comment]
Please send the link via dm on twitter 
Take a look at The Darkprogramer (@thedarkprogr): https://twitter.com/thedarkprogr?s=09

**Comment by xXxTheDarkprogramerxXx** [comment]
I have made a successful build with the debug build of the application and the release build as well 
I will be looking into this further i have sent you a pm with the link of your pkg 

Can you please tell me if your using one of the following settings ? 
is your emu set to default ?
is liborbis turned off in settings ?
are you using a custom temp path ?

**Comment by xXxTheDarkprogramerxXx** [comment]
Just for fullness before I Close this issue 

I was able to create the pkg on my end using the debug build

I have added the build from appvoyer you can get them in the release builds section
