### ISSUE TITLE
Grandia III with 2 Disks

### ISSUE THREAD

**Issue by camperschwein** [xXxTheDarkprogramerxXx/PS3Tools#26]
I will play Grandia III with 2 Disk on the PS4.
How can i do this ?
I have 2 ISOS from the 2 Disk and now ?
How can i Swapp the Disk in the PS4 ?

Best Regards

Tobi

**Comment by xXxTheDarkprogramerxXx** [comment]
HI Tobi ,

Simply slect both .sio files while holding down shift when the application asks you for an iso it will pop up the multi iso screen 

Then you will need to change the TITLE ID and the Title to create the PKG once created you can start the pkg on the ps4 

to swap disk(s) please hold down the ps button and select the disc number from the list 

Regards 
xDPx
