### ISSUE TITLE
Jak and Dexter Emu - error (PS2 PS4 1.0.0.20)

### ISSUE THREAD

**Issue by relaxfm** [xXxTheDarkprogramerxXx/PS3Tools#27]
![PS2](https://user-images.githubusercontent.com/31609899/62044559-ec477080-b20b-11e9-8f8f-304767255aee.png)

and update emu Jak and Dexter runs again and again....
(Win 8.1)
Brave - The Search for Spirit Dancer (Europe) SCES51635.

**Comment by xXxTheDarkprogramerxXx** [comment]
As stated on twitter im working on a fix for this please use the default emu
