### ISSUE TITLE
Confused with PSP on PS4 GUI

### ISSUE THREAD

**Issue by nanashi89** [xXxTheDarkprogramerxXx/PS3Tools#28]
Tried converting Mega Man Maverick Hunter X into a PKG. I got a PKG and GP4 file. What do I do with said files?

Used PS4 PSP Classics GUI.exe with the latest PS4.PSP.Classics.GUI.zip file, BTW.

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi Sorry for the extremely late reply i only saw it now 

Basically the PSP Emu for the ps4 is currently just trash 

as you can see from the compatibility list 
https://www.psdevwiki.com/ps4/PSP_Emulator_Compatibility_List


And Attempt is being made on getting a homebrew emulator to the public which will allow you to play more games 
https://trello.com/b/2MJwFHNs/sony-stuff

Regards 
xDPx
