### ISSUE TITLE
Video recording error and iso image compression

### ISSUE THREAD

**Issue by SSBVegeta** [xXxTheDarkprogramerxXx/PS3Tools#29]
Due to PS4 PS2 Classic GUI using Rogue v1 emulator as the default emulator, there is always a video recording error after launching a game.

https://imgur.com/1s1gp3k

The Rogue v2 emulator does not have this problem and should be used as the default.

Also is it possible to enable file compression for the created pkg file with PS4 PS2 Classic GUI like Fake PKG Generator allows for smaller PKG file and install size?

**Comment by xXxTheDarkprogramerxXx** [comment]
I can look at adding compression 

On the hand of Rogue your miss informed the default emu is max pain so not quite sure where you got your info

**Comment by SSBVegeta** [comment]
I got a PS2 emu templates pack a while ago from somewhere which had the emu you are using labelled as Rogue Galaxy v1. In that pack there is a Max Payne v2 emu with different CRCs to the one you are using. Perhaps the person who put the pack together is wrong.

In any case, is it possible to remove the recording error dialogue somehow with the Max Payne emu? I'm assuming you are using this emu because it has the highest compatibility out of all the emulators?
