### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by Shotkill20** [xXxTheDarkprogramerxXx/PS3Tools#3]
I use Burnout 3 takedown  FRA,DEU,IT   and my PS4 is in german.
The Game plays in Italy.

**Comment by xXxTheDarkprogramerxXx** [comment]
ill have a look at this for you

**Comment by Shotkill20** [comment]
Sorry its in France Not Italy thanks for looking👍🏻

**Comment by xXxTheDarkprogramerxXx** [comment]
Is there still something you would like to change for this ?

**Comment by Shotkill20** [comment]
I Cant Chance the Language to German the iso has 3 Languages. I  dont know why the Game plays in France. My PS4 is in German. And in Game is no Chance to change it.

**Comment by xXxTheDarkprogramerxXx** [comment]
you could change it perhaps by changing or adding this to your ps2 config 
--ps2-lang=system
that should sort it
