### ISSUE TITLE
I wonder if Klonoa 2's graphic bug is fix ? Sorry about my English and keep up the good work.

### ISSUE THREAD

**Issue by xXxTheDarkprogramerxXx** [xXxTheDarkprogramerxXx/PS3Tools#32]
I wonder if Klonoa 2's graphic bug is fix ? Sorry about my English and keep up the good work.

_Originally posted by @azoreseuropa in https://github.com/xXxTheDarkprogramerxXx/PS3Tools/issues/30#issuecomment-572816962_

Please open your own tickets so that we don't have mixed up tickets 
if you ever want to check if a game will work please use the link below
https://www.psdevwiki.com/ps4/PS2_Classics_Emulator_Compatibility_List

"Heavy glitches on characters models only in cutscenes (--fpu-no-clamping=1 on config file fixes misplaced items on stages). Check Emulator Configuration for additional details (Known in Japan as Kaze no Klonoa 2: Sekai ga Nozonda Wasuremono [風のクロノア2 世界が望んだ忘れもの])."

**Comment by spotanjo3** [comment]
Sorry about that. I did and it didn't work very well.. Still green wings balloons near the cave at the left instead of right which I need to jump over but I cannot.
