### ISSUE TITLE
PS2 iso compatibility issue

### ISSUE THREAD

**Issue by Nightscream2018** [xXxTheDarkprogramerxXx/PS3Tools#5]
Does your tool have a list of .isos that work with it?
Just tried SLUS-20393 Onimusha: Samurai's Destiny .iso with this and it will not go past PlayStation 2 logo screen. How to fix this issue?

**Comment by xXxTheDarkprogramerxXx** [comment]
You might need a custom config to fix this o some patches however currently the tool does not support custom patches it will be added at a later stage 

compatibility list can be found here 
http://www.psdevwiki.com/ps4/PS2_Classics_Emulator_Compatibility_List

Thanks for your feedback
