### ISSUE TITLE
original aspect ratio

### ISSUE THREAD

**Issue by asp0909** [xXxTheDarkprogramerxXx/PS3Tools#54]
How is the original aspect ratio set? the ps2 games are 4.3 ... and the guide only makes them wide ... and it looks awful!

**Comment by xXxTheDarkprogramerxXx** [comment]
https://www.psdevwiki.com/ps4/PS2_Emulation#config-emu-ps4.txt_commands
your welcome to add your own config file if you want something that the app does not define by default :)

**Comment by asp0909** [comment]
what is the command?

**Comment by xXxTheDarkprogramerxXx** [comment]
guessing this one --gs-aspect-ratio
