### ISSUE TITLE
PS2 GAME SİZE

### ISSUE THREAD

**Issue by Kazumatr** [xXxTheDarkprogramerxXx/PS3Tools#7]
PS2 CLASSİC GUi game created example 4gb game crate and install my ps4 pro game details game size 63,5 Gb o_O why ?

**Comment by xXxTheDarkprogramerxXx** [comment]
This was an old issue some of the users had experienced this is mainly do to them using a different hen then i used don't know why that would make a differenece tbh as the pkg itself is only 4gb and the content inside is not even close to 63 gb 

What firmware are you running on your pro ?

**Comment by Kazumatr** [comment]
System version 5.05
4 game creates and install every game 60+ gb size.
Fakepkg generator created game size is normal.

**Comment by xXxTheDarkprogramerxXx** [comment]
Fakepkg generator is the same as the one used in this app 


I updated to 5.05 today ill check it out in a bit

**Comment by Kazumatr** [comment]
Ok wait for your news bro.
Thank you support this.

**Comment by Kazumatr** [comment]
Update ?

**Comment by xXxTheDarkprogramerxXx** [comment]
Please try the latest update
