### ISSUE TITLE
New version doesn't load up.

### ISSUE THREAD

**Issue by Vashy-777** [xXxTheDarkprogramerxXx/PS3Tools#8]
I downloaded the latest version of ps4 ps2 classic gui. It updated and installed just fine. But when i click on it to load it, it just shows that it's loading up and then never opens. I have tried for the past 2 days to uninstall and reinstall it. Still nothing. Have any idea?

**Comment by xXxTheDarkprogramerxXx** [comment]
Id be lying if i told you 100% i have had some issue reported to me with regards to the custom path jot working as planed this kight be what causes your issue so i will add the check in a mew version soon please give me a few days 

Just need to sort out some other clients then i can focus on this
