### ISSUE TITLE
i can't connect 4 gamepads in ps2 games

### ISSUE THREAD

**Issue by SuhrobMuzrafkulov** [xXxTheDarkprogramerxXx/PS3Tools#9]
When i connect 4 gamepads, two of gamepads lighting white in ps2 games and these two gamepads don't work

**Comment by xXxTheDarkprogramerxXx** [comment]
HI I Believe my new update might sort this out for you @kozarovv sent me a newer version of the elf so it has more support for games i will be updating soon with custom patches as well

**Comment by ghost** [comment]
@SuhrobMuzrafkulov Add this two lines to config file:

--mtap1=always
--mtap2=always

**Comment by xXxTheDarkprogramerxXx** [comment]
@kozarovv thanks for that

**Comment by K-ille-R** [comment]
@kozarovv  @xXxTheDarkprogramerxXx  how do I add the lines to the config file , would you mind helping me with that ?

**Comment by xXxTheDarkprogramerxXx** [comment]
https://github.com/xXxTheDarkprogramerxXx/PS3Tools/blob/master/PS4%20PS2%20Classis%20GUI/PS4%20PS2%20Classis%20GUI/bin/Debug/PS2.zip

Inside that zip is the config file you can edit it as you wish

**Comment by K-ille-R** [comment]
@xXxTheDarkprogramerxXx @kozarovv welp , I added your two commands , still can’t connect more than 2 controller

**Comment by ghost** [comment]
Are you sure you added correct txt file to pkg? Which game it is? Post your current config file here.

**Comment by K-ille-R** [comment]
@kozarovv what do you mean add the txt file to pkg , I just added the lines to the txt and used it on the ps2 classics gui 
[config-emu-ps4.txt](https://github.com/xXxTheDarkprogramerxXx/PS3Tools/files/2095689/config-emu-ps4.txt) 
I tried two games , Def Jam Fight for ny (SLES52507) and NBA Street V2 (SLUS20651).
Also , thanks for helping.

**Comment by xXxTheDarkprogramerxXx** [comment]
@K-ille-R did you add the config via the gui ?

**Comment by ghost** [comment]
@K-ille-R try with this: 
[config-emu-ps4.txt](https://github.com/xXxTheDarkprogramerxXx/PS3Tools/files/2096506/config-emu-ps4.txt)

**Comment by K-ille-R** [comment]
@xXxTheDarkprogramerxXx  yeah , I tapped file then "add custom config" so yeah and @kozarovv will try this now , hope it works.
Thanks guys

**Comment by K-ille-R** [comment]
@kozarovv  I love you , IT WORKED but unfortunately only for NBA Street V2 , Def Jam Fight for NY still wouldn't recognize more than 2 controllers.

**Comment by SuhrobMuzrafkulov** [comment]
Try to add only --mtap1=always, and connect 4 controllers in def jam fight for NY. and you can play only 3 players because the second port doesn't work
